### ISSUE TITLE
All functions should be tested at least once

### ISSUE THREAD

**Issue by Lysxia** [Lysxia/first-class-families#24]
This would have prevented issue #23 for instance.

**Comment by gspia** [comment]
Good idea!

The doc tests that you added couple of days ago work nicely as a unit tests? If yes, they would nicely serve two purposes at the same time. Just wondering, is it possible to use some of the testing libs (validity/hedgehog) by connecting the  type-level calcs and their results to term level.

**Comment by Lysxia** [comment]
That's right, doctests for all functions would be sufficient.

There doesn't seem to be an easy way to integrate with conventional testing libraries because everything happens at compile time here.

**Comment by Lysxia** [comment]
Pretty well covered with e361c72
