### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gspia** [Lysxia/first-class-families#27]
Hi!

Are planning to do a release soon or will you want to get some things done on this Fcf lib first?

I'm asking this since I'm planning to release a new lib that would use Fcf as the main dependency :)

On the forthcoming lib will be things that might fit better into this Fcf. And I hope that you will have time to take a look of the code then and maybe give some comments? And we could possibly talk about moving some of the functions from the forthcoming lib into Fcf? 

Anyhow, this is taking my time at the moment. And based on when you are going to release a new version, I might make a separate module that will contain some of the functions that are going to be released in Fcf (and then remove that module when you do release Fcf). E.g. I need the Elem correction and some other list functions.

On nix I can refer to unreleased version but I'd really like to try to do a hackage-package at the same time.

**Comment by Lysxia** [comment]
I'm planning a release some time next week.

Don't hesitate to ask me for comments on your library!

Note that the `Elem` bug was introduced when it became `data`, so it does not exist at all on Hackage since there was no release in the meantime.

**Comment by gspia** [comment]
Hi

Couldn't resist any more :)


    Downloads | 0 total (0 in the last 30 days)
    -- | --

So I made my first hackage package just minutes ago. If you have time, please do check it
[at github](https://github.com/gspia/fcf-containers)
or
[at hackage](http://hackage.haskell.org/package/fcf-containers-0.1.0)

I ended up to referring to fcf 0.6 and took couple of function from fcf. I'll remove those from fcf-containers once you release a new version and then I'll do a new release.

I have to admit that some of the names were really hard to choose. And they might should be changed.

**Comment by Lysxia** [comment]
[0.7.0.0](https://hackage.haskell.org/package/first-class-families-0.7.0.0) is out!
