### ISSUE TITLE
Support GHC 8.10

### ISSUE THREAD

**Issue by chshersh** [Lysxia/first-class-families#37]
It would be nice if `first-class-families` could be built with GHC-8.10. I wonder, whether bumping bounds would be enough.

**Comment by Lysxia** [comment]
I'll try bumping the bound and see what Travis CI thinks of it.

**Comment by Lysxia** [comment]
It works! I'll make a revision on Hackage and then merge #38.

**Comment by chshersh** [comment]
@Lysxia Thanks a lot for the quick fix!
