### ISSUE TITLE
Export `Fcf.Combinators.(>>=)`

### ISSUE THREAD

**Issue by gspia** [Lysxia/first-class-families#51]
The export list looks like 
```
module Fcf.Combinators
  ( Pure
  , Pure1
  , Pure2
  , Pure3
  , type (=<<)
  , type (<=<)
  , LiftM
  , LiftM2
  , LiftM3
  , Join
  , type (<$>)
  , type (<*>)
  , Flip
  , ConstFn
  , type ($)
  ) where
```

Would exporting also the `Fcf.Combinators.(>>=)` be ok?

(This was partly touched  at https://github.com/gspia/fcf-containers/issues/15.)

**Comment by Lysxia** [comment]
This was actually added in the source a while back (https://github.com/Lysxia/first-class-families/pull/14) but I forgot to export it... Will be exported in the upcoming release.
